name: Johannes de Boer
favicon: null
layout_spectrum: 0.5571604617871344
typography_spectrum: 0.7979751001112163
title: My personal website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-11610311-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bedbf2'
    - '#000000'
    - '#754c2e'
    - '#fffeb7'
    - '#6c7f8c'
  brandStrength: 0.375
  lightness: 0.49038230907171965
  saturation: 0.5718190239276737
  rhythmicContrast: 0.8306448748335242
purpose: []
